### ISSUE TITLE
Hard stop error

### ISSUE THREAD

**Issue by HibikiFox** [j-e-k/poketrainer#170]
Getting this error at random during the run since last update
```
[ERROR] Error in main loop, restarting %s
Traceback (most recent call last):
  File "pokecli.py", line 121, in main
    api.main_loop()
  File "%path%\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 846, in main_loop
    self.spin_all_forts_visible()
  File "%path%\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 389, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "%path%\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 297, in walk_to
    self.spin_nearest_fort()
  File "%path%\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 333, in spin_nearest_fort
    fort_distance=nearest_fort_dis)
  File "%path%\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 348, in fort_search_pgoapi
    for item in res['items_awarded']:
KeyError: 'items_awarded'
```

*replaced base directory path with %path% for security*

**Comment by STJudd109** [comment]
I'm getting the same error

**Comment by fnk93** [comment]
Same problem here.
Item Bag filled up, Bot continued to walk to two or three other stops and then constantly crashed even when relogging

**Comment by HibikiFox** [comment]
Mine is happening with room to spare in my item bag, So I don't think a full bag is the problem

**Comment by destiny117** [comment]
Maybe you are softbanned and thus not receiving any items? I will check it out and make a PR to eventually eliminate the error

**Comment by HibikiFox** [comment]
@destiny117 

It still runs and collects items, but something is causing that stop at random... My guess would be a Lured pokestop, it used to mention those in the run, but I do not see it anymore and I know I am in an area where lures are common, however I do not see "Pokestop with active Lure" anymore...

thoughts?

**Comment by sontek** [comment]
https://github.com/j-e-k/poketrainer/pull/176  Fixes this

**Comment by destiny117** [comment]
as far as i know it only ever mentioned lured pokestops when it encounters a pokemon there (because of the lure), and it still does so

however your step-count might be a bit high and you are encountering very short soft-bans which prevent you from spinning pokestops at times (my guess), and yes i made PR #176 to fix it

**Comment by sontek** [comment]
Its not a softban, it looks like sometimes it just doesn't fill out the result.  I'm seeing it as well.

**Comment by sontek** [comment]
Although it could be a super short softban, my step size is 6 and I'm seeing this.

**Comment by destiny117** [comment]
the reson why i think it might be softbans is because i ran it like this for hours with <100m stepcounts and never encountered it :)

**Comment by HibikiFox** [comment]
I use `6` for steps... I don't wanna be a complete retard lol

**Comment by sontek** [comment]
It could just be that they are having issues as well though since its giving result 1 with an empty body

**Comment by j-e-k** [comment]
Sorry was on a call, will get this done now

**Comment by j-e-k** [comment]
Just merged in PR from @sontek , are you still getting this?

**Comment by HibikiFox** [comment]
@j-e-k 

I will test and let you know, It is hard to catch because of the auto restart after a time, So it might take a bit

**Comment by HibikiFox** [comment]
@j-e-k @sontek 

Got this now, not sure if it is related
```
2016-07-27 17:40:08,809 [    pgoapi] [ERROR] There were a problem responses for api call: None. Restarting!!!
2016-07-27 17:40:08,809 [   pokecli] [ERROR] Error in main loop, restarting %s
Traceback (most recent call last):
  File "pokecli.py", line 121, in main
    api.main_loop()
  File "%path%\poketrainer-develop\pgoapi\pgoapi.py", line 846, in main_loop
    self.spin_all_forts_visible()
  File "%path%\poketrainer-develop\pgoapi\pgoapi.py", line 389, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "%path%\poketrainer-develop\pgoapi\pgoapi.py", line 297, in walk_to
    self.spin_nearest_fort()
  File "%path%\poketrainer-develop\pgoapi\pgoapi.py", line 328, in spin_nearest_fort
    self.walk_to_fort(destinations[0], directly=True)
  File "%path%\poketrainer-develop\pgoapi\pgoapi.py", line 399, in walk_to_fort
    self.walk_to((fort['latitude'], fort['longitude']), directly=directly)
  File "%path%\poketrainer-develop\pgoapi\pgoapi.py", line 293, in walk_to
    self.heartbeat()
  File "%path%\poketrainer-develop\pgoapi\pgoapi.py", line 211, in heartbeat
    raise AuthException("Token probably expired?")
AuthException: Token probably expired?
```

hard to tell for me since I don't know python very well

**Comment by destiny117** [comment]
i would assume servers are a bit busy and you can get some bad responses from time to time which results in such errors.
or your login token actually expired? idk exaclty

however this is not directly related to the code-bug which caused the initial error

**Comment by HibikiFox** [comment]
Appears fine then, I haven't seen the same error for about 30 minutes now and it has visited all of the pokestops in the same area where the error was happening.

I will continue to monitor for this, but I would consider this fixed @j-e-k @destiny117 @sontek

**Comment by j-e-k** [comment]
Ok, I merged changes into master just now (there was also a bug hiding in the pokemon release code...)

**Comment by sontek** [comment]
My fix didn't quite fix it, I'm still seeing error responses:

```
2016-07-27 23:12:51,566 [    pgoapi] [ INFO] ============== ERROR RESULT WAS WEIRD: {}
2016-07-27 23:12:51,567 [    pgoapi] [ INFO] Could not spin fort http://maps.google.com/maps?q=26.310764,-80.078624, Error id: 1
```

Not sure why my logic didn't prevent that but I'll fix it

**Comment by j-e-k** [comment]
Bah, will reopen issue then. summon me when you have a fix

**Comment by sontek** [comment]
@j-e-k I think you can keep this closed, the only time I experienced my fix not working was while the server was having issues and I was never able to reproduce to see what it was actually returning... But it had returned status 1 but had other keys in the dictionary but didn't have the ones we were expecting

**Comment by sontek** [comment]
We can re-open if we ever experience it again but I assume it was just a weird glitch on their side

**Comment by destiny117** [comment]
@sontek 

`Could not spin fort http://maps.google.com/maps?q=xxx,yyy, Error id: 1`

is exactly the output you will get when your fix works :) if you would still want to get a positive return, take a look at the method i used in #176 

pretty sure this is still fixed and what you saw was what you should see, when the error occurs
