### ISSUE TITLE
KeyError: 'start_km_walked'

### ISSUE THREAD

**Issue by stef264** [j-e-k/poketrainer#262]
Always getting this error:

http://pastebin.com/gk5sUHeN

**Comment by azgul** [comment]
#263 should fix this :) It worked for me

**Comment by chrisconcepcion** [comment]
I just pulled the latest code and am still having this issue


http://pastebin.com/zZwhb3CA

**Comment by azgul** [comment]
@chrisconcepcion  it was merged into develop branch, not master :) try develop

**Comment by j-e-k** [comment]
Just cherry picked this into master. Should work now
